---
- name: install mysql
  hosts: 
    - localhost
  roles:
    - role: geerlingguy.mysql
      become: yes
  vars:
    mysql_packages:
      - mysql-client
      - mysql-server
    mysql_user_home: /root
    mysql_user_name: root
    mysql_root_password: 
    mysql_root_password_update: no
    #第一次安装不要更改密码
    mysql_enabled_on_startup: true
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
  tasks:
  - name: restart mysql
    command: service mysql restart
